
upmci_registry: https://artifactory.prd.cds.internal.unity3d.com/artifactory/api/npm/upm-npm

test_editors:
  - version: 2019.3.15f1

publish_editors:
  - version: 2019.3.15f1

publish_platforms:
  - name: win
    type: Unity::VM
    image: package-ci/win10:stable
    flavor: b1.large
    extra-args: --force-d3d11
    standalone-platform: StandaloneWindows64
  - name: mac
    type: Unity::VM::osx
    image: package-ci/mac:stable
    flavor: m1.mac
    extra-args: --force-metal
    standalone-platform: StandaloneOSX
  - name: ubuntu
    type: Unity::VM
    image: package-ci/ubuntu:latest
    flavor: b1.large


test_platforms:
  - name: win
    type: Unity::VM
    image: package-ci/win10:stable
    flavor: b1.large
    extra-args: --force-d3d11
    standalone-platform: StandaloneWindows64
  - name: mac
    type: Unity::VM::osx
    image: package-ci/mac:stable
    flavor: m1.mac
    extra-args: --force-metal
    standalone-platform: StandaloneOSX
  - name: ubuntu
    type: Unity::VM
    image: package-ci/ubuntu:latest
    flavor: b1.large

suites:
  - name: standalone
    display_name: standalone
    args: --suite=playmode --platform=
  - name: editmode
    display_name: editmode
    args: --suite=playmode --suite=editor --platform=editmode

package_variants:
  - name: Perception

projects:
  - name: PerceptionHDRP
  - name: PerceptionURP
